spring.application.name=email-service

### AWS ###
acessKeyId=${AWS_ACESS_KEY_ID}
secretKey=${AWS_SECRET_KEY}
region=${AWS_REGION}


gridkey=${SENDGRID_API_KEY}


### RABBITMQ ###
spring.rabbitmq.addresses=${RABBITMQ_ADRESS}
spring.rabbitmq.queue=${RABBITMQ_NAME_QUEUE}


### EMAIL ###
from.email=${EMAIL_FROM}




